apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationmappings.applicationconnector.kyma-project.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: applicationconnector.kyma-project.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: applicationmappings
    singular: applicationmapping
    kind: ApplicationMapping
    shortNames:
    - am
