apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: certificaterequests.applicationconnector.kyma-project.io
spec:
  group: applicationconnector.kyma-project.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            properties:
              csrInfoUrl:
                type: string
            required:
            - csrInfoUrl
            type: object
  names:
    kind: CertificateRequest
    singular: certificaterequest
    plural: certificaterequests
  scope: Cluster
