apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventactivations.applicationconnector.kyma-project.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: applicationconnector.kyma-project.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              sourceId:
                type: string
                minLength: 1
                maxLength: 253
                pattern: '^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?)*$'
              displayName:
                type: string
  scope: Namespaced
  names:
    plural: eventactivations
    singular: eventactivation
    kind: EventActivation
    shortNames:
    - ea
