deployment:
  image:
    pullPolicy: IfNotPresent
  args:
    proxyOSPort: &proxyOSPort 8080
    proxyMPSPort: &proxyMPSPort 8082
    externalAPIPort: &externalAPIPort 8081
    requestTimeout: 10
    skipVerify: false
    proxyTimeout: 10
    proxyCacheTTL: 120
    requestLogging: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

service:
  externalapi:
    port: *externalAPIPort
  proxy:
{{- if not .Values.global.disableLegacyConnectivity }}
    port: *proxyOSPort
{{-else}}
    port: *proxyMPSPort
{{- end }}

# ONLY FOR KYMA OS implementation

autoscaling:
  enable: true
  minReplicas: 1
  maxReplicas: 10
  cpuUsagePercent: 40